glossar_all:
  path: /xhr/glossar
  defaults:
    _controller: ContaoGlossarBundle:Word:findAll
    _scope: fontend
    _token_check: false
glossar_entry:
  path: /xhr/glossar/{strWord}
  defaults:
    _controller: ContaoGlossarBundle:Word:find
    _scope: fontend
    _token_check: false
    strWord: "null"