services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  LumturoNet\ContaoGlossarBundle\:
    resource: ../../../src
    exclude: ../../../src/{Entity,Migrations,Model,Resources,Tests,Widget}

  LumturoNet\ContaoGlossarBundle\Controller\:
    resource: ../../../src/Controller
    public: false